const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub6.js','utf8');
const out=[]; const ok=(n,p,i='')=>console.log(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const errs=[];
  const page = async (init) => { const p=await (await b.newContext({viewport:{width:390,height:844}})).newPage(); p.on('pageerror',e=>errs.push(e.message));
    await p.addInitScript(init);
    await p.route(/functions\/v1\//, r=>r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{"ok":true}'}));
    await p.route(/^https:\/\/(?!cdn\.jsdelivr)(?!.*functions\/v1)/, r=>r.abort());
    await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub}));
    await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
    await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(1800); return p; };
  let p = await page(`window.__NOSESSION__=true; window.__PWERR__=true;`);
  ok('Email box is a sign-in username, no autocapitalise', (await p.getAttribute('#authEmail','autocomplete'))==='username' && (await p.getAttribute('#authEmail','autocapitalize'))==='off');
  await p.fill('#authEmail','Rakshithr12321@gmail.com '); await p.fill('#authPass','whatever1'); await p.click('[data-action=authPassword]'); await p.waitForTimeout(500);
  const m = (await p.textContent('.status')).trim();
  ok('Wrong password names the email tried', /Wrong password for rakshithr12321@gmail\.com/.test(m) && /email your phone filled in/.test(m), m);
  p = await page(`window.__MEMBER__={status:'declined'}; window.__USER__={id:'u9', email:'rakshithr12321@gmail.com', user_metadata:{}};`);
  const t = (await p.textContent('#main')).replace(/\s+/g,' ');
  ok('Declined screen says which email and how to switch', /You signed in as rakshithr12321@gmail\.com/.test(t) && /Sign out and use another email/.test(t), t.slice(0,220));
  await (await p.$('#main section')).screenshot({path:__dirname+'/declined.png'});
  ok('No page errors', !errs.length, errs.join(' | ')); await b.close(); })();
