const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub6.js','utf8');
const ok=(n,p,i='')=>console.log(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const errs=[];
  const run = async (reachable, ua) => { const ctx = await b.newContext({viewport:{width:390,height:844}, userAgent: ua}); const p=await ctx.newPage(); p.on('pageerror',e=>errs.push(e.message));
    await p.addInitScript(`window.__NOSESSION__=true; window.__NETERR__=true;`);
    await p.route(/supabase\.co\/auth\/v1\/health/, r => reachable ? r.fulfill({status:401, body:'{}'}) : r.abort('namenotresolved'));
    await p.route(/functions\/v1\//, r=>r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{"ok":true}'}));
    await p.route(/^https:\/\/(?!cdn\.jsdelivr)(?!.*functions\/v1)(?!.*auth\/v1\/health)/, r=>r.abort());
    await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub}));
    await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
    await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(1800);
    await p.fill('#authEmail','rakshithkumar12321@gmail.com'); await p.fill('#authPass','whatever1'); await p.click('[data-action=authPassword]'); await p.waitForTimeout(1200);
    const m = (await p.textContent('.status')).trim(); if (!reachable && /Android/.test(ua)) await (await p.$('#main section')).screenshot({path:__dirname+'/blocked.png'}); await ctx.close(); return m; };
  const AND = 'Mozilla/5.0 (Linux; Android 14; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0 Mobile Safari/537.36';
  const IOS = 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1';
  let m = await run(false, AND); ok('Android, server blocked: Private DNS steps', /blocking MaxxTempo’s server/.test(m) && /dns\.google/.test(m), m);
  m = await run(false, IOS); ok('iPhone, server blocked: 1.1.1.1 app', /1\.1\.1\.1/.test(m), m);
  m = await run(true, AND); ok('Server reachable: normal message with the reason', /Check your connection/.test(m) && /Failed to fetch/.test(m) && !/dns\.google/.test(m), m);
  ok('No page errors', !errs.length, errs.join(' | ')); await b.close(); })();
