const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub2.js','utf8'); const seed = JSON.parse(fs.readFileSync(__dirname+'/seed.json','utf8'));
const out=[]; const ok=(n,p,i='')=>console.log(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const p=await (await b.newContext({viewport:{width:390,height:844}})).newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
  await p.addInitScript(`window.__SEED__=${JSON.stringify(seed)};`);
  const calls=[]; let delay=0;
  await p.route(/functions\/v1\/claude/, async r => { const d=JSON.parse(r.request().postData()||'{}'); calls.push(d.task);
    if (d.task==='usage') return r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({ok:true,ready:true,usage:{count:0,cap:30}})});
    if (delay) await new Promise(z=>setTimeout(z,delay));
    if (d.task==='log') { const entry=(d.prompt||'').split('Entry: """')[1]||'';
      return r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({ok:true,json:{foods:[],exercises:[],activities:/kabaddi/i.test(entry)?[{sport:'Kabaddi',entry:'kabaddi 1 hour'}]:[],supplements:[],water_ml:0,notes:''},usage:{count:1,cap:30}})}); }
    return r.fulfill({status:503,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({ok:false,code:'busy'})}); });
  await p.route(/functions\/v1\/(?!claude)/, r=>r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{"ok":true,"passkeys":[],"connected":false}'}));
  await p.route(/^https:\/\/(?!cdn\.jsdelivr)(?!.*functions\/v1)/, r=>r.abort());
  await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub}));
  await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
  await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(2000);
  const st = async()=> (await p.textContent('#logStatus').catch(()=>''))||'';
  const main = async()=> (await p.textContent('#main')).replace(/\s+/g,' ');
  const log = async (t, w=900) => { calls.length=0; await p.fill('#logText',t,{timeout:5000}).catch(async e=>{console.log('FILL FAIL', (await p.textContent('#main')).replace(/\s+/g,' ').slice(0,600)); throw e;}); await p.click('[data-action=log]'); await p.waitForTimeout(w); };
  await log('cb peri peri chicken burrito, extra paneer, guacamole'); let s = await st();
  ok('Typed CB order logs without AI', !calls.filter(c=>c!=='usage').length && /1 food · 1,?187 kcal/.test(s), `${calls} | ${s}`);
  await log('california burrito mexican paneer rice bowl and 1 banana'); s = await st();
  ok('CB bowl + other food, no AI', !calls.filter(c=>c!=='usage').length && /2 foods/.test(s), s);
  await p.click('[data-fold=d-food] summary').catch(()=>{}); await p.waitForTimeout(300);
  const t = (await main());
  ok('Shows in what I ate', /California Burrito Crispy Peri Peri Chicken Burrito \(Regular\) \+ extra mexican paneer, guacamole/.test(t), t.match(/California Burrito[^·]{0,90}/)?.[0]);
  await log('California pro salad bowl with extra chicken'); s = await st();
  ok('Screenshot case: 786 kcal, no AI', !calls.filter(c=>c!=='usage').length && /786 kcal/.test(s), `${calls} | ${s}`);
  await log('California chicken pro salad bowl with add on chicken, half california cheesy chicken dominator quesadilla and 1 chicken taco'); s = await st();
  ok('Whole dinner entry, no AI', !calls.filter(c=>c!=='usage').length && /3 foods · 1,?(1|2)\d\d kcal/.test(s), `${calls} | ${s}`);
  const t2 = await main();
  ok('Fibre and half portion recorded', /half quesadilla/.test(t2) && /786/.test(t2), (t2.match(/California Burrito Grilled[^]{0,120}/)||[''])[0]);
  // picker
  await p.click('[data-action=foodSearch]'); await p.waitForTimeout(300); await p.click('#fcb'); await p.waitForTimeout(300);
  const tot = async () => (await p.textContent('.cbtotal')).replace(/\s+/g,' ');
  ok('Picker opens with a rice bowl', /kcal/.test(await tot()), await tot());
  await p.selectOption('#cb_meal','burrito'); await p.waitForTimeout(200);
  await p.selectOption('[data-s=protein]','CRISPY PERI PERI CHICKEN'); await p.waitForTimeout(200);
  await p.check('[data-g=extraFillings][value="MEXICAN PANEER"]'); await p.waitForTimeout(200);
  await p.check('[data-g=makeItRich][value="GUACAMOLE"]'); await p.waitForTimeout(200);
  ok('Picker total matches the typed order', /1,187 kcal/.test(await tot()), await tot());
  await (await p.$('.cbform')).screenshot({path:__dirname+'/cb-picker.png'});
  await p.click('#cbform button[type=submit]'); await p.waitForTimeout(600);
  ok('Picker logs it', /Logged California Burrito Crispy Peri Peri Chicken Burrito/.test(await st()), await st());
  ok('No page errors', !errs.length, errs.join(' | ')); console.log(out.join('\n')); await b.close(); })();
