const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub2.js','utf8'); const seed = JSON.parse(fs.readFileSync(__dirname+'/seed.json','utf8'));
const out=[]; const ok=(n,p,i='')=>out.push(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844}}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
  await p.addInitScript(`window.__SEED__=${JSON.stringify(seed)};`); await p.route(/^https:\/\/(?!cdn\.jsdelivr)/, r=>r.abort());
  await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub})); await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
  await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(1300);
  const fibreRow = async () => (await p.$$eval('.mrow', rs=>rs.map(r=>r.textContent.replace(/\s+/g,' ').trim()).find(t=>/^Fibre/.test(t))||''));
  const before = await fibreRow();
  await p.click('.tab[data-view=profile]'); await p.click('[data-fold=p-goals] summary'); await p.waitForTimeout(150);
  ok('Daily goals has a Fibre box', !!(await p.$('#pf_fibre')), 'placeholder: '+await p.getAttribute('#pf_fibre','placeholder'));
  await p.fill('#pf_fibre','40'); await p.click('[data-fold=p-goals] button[type=submit]'); await p.waitForTimeout(300);
  ok('Saved fibre goal shows as yours', /Fibre yours\s*40 g/.test((await p.textContent('[data-fold=p-goals] .fold-body')).replace(/\s+/g,' ')));
  await p.click('.tab[data-view=today]'); await p.waitForTimeout(200); const after = await fibreRow();
  ok('Today uses the fibre goal', /\/ 40 g/.test(after), `${before}  →  ${after}`);
  await p.click('#menuBtn'); await p.click('#prevDay'); await p.click('#prevDay'); await p.click('#menuClose'); await p.waitForTimeout(200);
  ok('A training day keeps the same fibre goal', /\/ 40 g/.test(await fibreRow()), await fibreRow());
  await p.click('[data-action=goToday]'); await p.click('.tab[data-view=profile]'); await p.fill('#pf_fibre',''); await p.click('[data-fold=p-goals] button[type=submit]'); await p.waitForTimeout(300);
  await p.click('.tab[data-view=today]'); await p.waitForTimeout(200); ok('Clearing it goes back to the suggested fibre', (await fibreRow())===before, await fibreRow());
  ok('no page errors', !errs.length, errs.join('|')); console.log(out.join('\n')); await b.close(); })();
