const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const fs = require('fs');
const stub = fs.readFileSync(__dirname + '/stub-supabase.js', 'utf8');
const seed = JSON.parse(fs.readFileSync(__dirname + '/seed.json','utf8'));
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport:{width:390,height:844}, colorScheme:'dark' });
  const p = await ctx.newPage(); const errs=[]; p.on('pageerror', e=>errs.push(e.message));
  await p.addInitScript(`window.__SEED__=${JSON.stringify(seed)};`);
  await p.route(/^https:\/\/(?!cdn\.jsdelivr|fonts)/, r => r.abort());
  await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r => r.fulfill({ contentType:'application/javascript', body: stub }));
  await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
  await p.goto('http://localhost:8765/', { waitUntil:'load' }); await p.waitForTimeout(1200);
  const shot = async n => { await p.screenshot({ path:`${__dirname}/final/${n}.png` }); console.log('shot', n); };
  await p.fill('#logText', '2 roti, 1 katori dal, 200 g curd rice, 500 ml water'); await p.click('[data-action=log]'); await p.waitForTimeout(600);
  await shot('auto-dark');
  await p.click('#menuBtn'); await p.waitForTimeout(200); await p.click('[data-action=theme][data-t=light]'); await p.waitForTimeout(300);
  console.log('after Light: data-theme =', await p.evaluate(()=>document.documentElement.dataset.theme), '| meta =', await p.evaluate(()=>document.querySelector('meta[name=theme-color]').content), '| stored =', await p.evaluate(()=>localStorage.getItem('mt:theme')));
  await shot('menu-light');
  await p.click('#prevDay'); await p.waitForTimeout(200); await p.click('#menuClose'); await p.waitForTimeout(200);
  await shot('light-pastday'); console.log('past bar:', await p.textContent('.pastbar').catch(()=>'none'));
  await p.click('[data-action=goToday]'); await p.waitForTimeout(200); console.log('past bar gone:', !(await p.$('.pastbar')));
  await p.reload({ waitUntil:'load' }); await p.waitForTimeout(1200); console.log('after reload: data-theme =', await p.evaluate(()=>document.documentElement.dataset.theme));
  await p.click('.tab[data-view=trends]'); await p.waitForTimeout(300); await shot('light-trends');
  await p.click('.tab[data-view=gym]'); await p.waitForTimeout(300); await shot('light-train');
  await p.click('#menuBtn'); await p.click('[data-action=theme][data-t=dark]'); await p.click('#menuClose'); await p.click('.tab[data-view=today]'); await p.waitForTimeout(300); await shot('dark-today');
  await p.click('#menuBtn'); await p.click('[data-action=theme][data-t=auto]'); console.log('auto: data-theme =', await p.evaluate(()=>document.documentElement.dataset.theme ?? '(none)'), '| stored =', await p.evaluate(()=>localStorage.getItem('mt:theme')));
  console.log('errors', errs); await b.close();
})();
