const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub3.js','utf8'); const seed = JSON.parse(fs.readFileSync(__dirname+'/seed.json','utf8'));
const prof = seed.find(r=>r.collection==='profile'); prof.data.stack = [{id:'mv', name:'Multivitamin', dose:'1 tablet', micros:{iron_mg:10, zinc_mg:22, vitamin_a_mcg:1900, vitamin_c_mg:60, vitamin_d_mcg:10, vitamin_b12_mcg:4.6, folate_mcg:600, calcium_mg:5, magnesium_mg:4}}];
const out=[]; const ok=(n,p,i='')=>out.push(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844}, hasTouch:true, isMobile:true}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
  await p.addInitScript(`window.__SEED__=${JSON.stringify(seed)};`);
  await p.route(/functions\/v1\//, r=>r.fulfill({status:200,contentType:'application/json',body:'{"ok":true,"ready":true,"usage":{"count":0,"cap":30},"passkeys":[],"connected":false}'}));
  await p.route(/^https:\/\/(?!cdn\.jsdelivr)(?!.*functions\/v1)/, r=>r.abort());
  await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub}));
  await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
  await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(2500);
  const sec = await p.$('[aria-label="Vitamins and minerals"]'); await sec.scrollIntoViewIfNeeded();
  const note = await p.textContent('.micnote').catch(()=>null);
  ok('Panel says the numbers include the multivitamin, added automatically', note && /Multivitamin/.test(note) && /automatically/.test(note), note);
  const zinc = await p.evaluate(()=>{ const r=[...document.querySelectorAll('.facts .fr')].find(x=>/^Zinc/.test(x.textContent.trim())); return r && [...r.querySelectorAll('.bar i')].map(i=>(i.className||'food')+':'+i.style.width); });
  ok('Zinc bar is all supplement (lighter part)', zinc && zinc.some(x=>x.startsWith('sp:100')) && zinc.some(x=>x==='food:0%'), JSON.stringify(zinc));
  await sec.screenshot({path:__dirname+'/micnote.png'});
  ok('No page errors', !errs.length, errs.join(' | '));
  console.log(out.join('\n')); await b.close(); })();
