const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub3.js','utf8'); const seed = JSON.parse(fs.readFileSync(__dirname+'/seed.json','utf8'));
const out=[]; const ok=(n,p,i='')=>out.push(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const p=await (await b.newContext({viewport:{width:390,height:844}, ignoreHTTPSErrors:true})).newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
  await p.context().route(/cdn\.jsdelivr\.net\/npm\/(tesseract|@tesseract)/, async r => { const res = await fetch(r.request().url()); const buf = Buffer.from(await res.arrayBuffer()); r.fulfill({status:res.status, headers:{'access-control-allow-origin':'*','content-type':res.headers.get('content-type')||'application/octet-stream'}, body:buf}); });
  await p.addInitScript(`window.__SEED__=${JSON.stringify(seed)};`);
  await p.route(/functions\/v1\/claude/, r => { const d=JSON.parse(r.request().postData()||'{}');
    const entry=(d.prompt||'').split('Entry: """')[1]||''; const res = d.task==='usage' ? {ok:true,ready:true,usage:{count:0,cap:30}} : {ok:true, json:{foods:[...(/chai/.test(entry)?[{name:'Masala chai',quantity:'1 cup',grams:150,kcal:90,protein_g:3,carbs_g:12,fat_g:3,sugar_g:10,added_sugar_g:7,confidence:'medium'}]:[]),{name:'Mango smoothie with dates',quantity:'1 glass',grams:300,kcal:250,protein_g:5,carbs_g:50,fat_g:3,sugar_g:40,added_sugar_g:18,confidence:'medium'}],exercises:[],activities:[],supplements:[],water_ml:0,notes:''}, usage:{count:1,cap:30}};
    r.fulfill({status:200, contentType:'application/json', headers:{'access-control-allow-origin':'*'}, body:JSON.stringify(res)}); });
  await p.route(/functions\/v1\/(?!claude)/, r=>r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{"ok":true,"passkeys":[],"connected":false}'}));
  await p.route(/world\.openfoodfacts\.org/, r=>r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{"status":0}'}));
  await p.route(/^https:\/\/(?!cdn\.jsdelivr)(?!.*functions\/v1)(?!world\.openfoodfacts)/, r=>r.abort());
  await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub}));
  await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
  await p.addInitScript(`window.__SHARED__={code:'8909999000011',name:'Group Chikki',per:{kcal:480,protein:12,carbs:60,fat:22,fiber:3,sugar:35,added_sugar:30,micros:{sat_fat_g:4,sodium_mg:20}},units:{packet:40}};`);
  await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(2000);
  await p.click('[data-action=scan]'); await p.waitForTimeout(400); await p.fill('#codein','8909999000011'); await p.click('#codeform button'); await p.waitForTimeout(1200);
  const t = (await p.textContent('#dlg')).replace(/\s+/g,' ');
  ok('Group pack found instantly', /Group Chikki/.test(t) && /added from the label by someone in your group/.test(t) && await p.isVisible('#pform'), t.slice(0,140));
  await p.click('#pform button[type=submit]'); await p.waitForTimeout(700);
  ok('Logs a 40 g packet', /Group Chikki · 192 kcal/.test(await p.textContent('#logStatus')), await p.textContent('#logStatus'));
  ok('No page errors', !errs.length, errs.join(' | ')); console.log(out.join('\n')); await b.close(); })();
