const { chromium } = require('/opt/node22/lib/node_modules/playwright'); const fs=require('fs');
const stub = fs.readFileSync(__dirname+'/stub4.js','utf8'); const seed = JSON.parse(fs.readFileSync(__dirname+'/seed.json','utf8'));
const out=[]; const ok=(n,p,i='')=>out.push(`${p?'PASS':'FAIL'}  ${n}${i?'  — '+i:''}`);
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844}}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('dialog', d=>d.type()==='prompt'?d.accept('Push day'):d.accept());
  await p.addInitScript(`window.__SEED__=${JSON.stringify(seed)};`);
  await p.route(/functions\/v1\//, r=>r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'{"ok":true,"ready":true,"usage":{"count":0,"cap":30},"passkeys":[],"connected":false}'}));
  await p.route(/^https:\/\/(?!cdn\.jsdelivr)(?!.*functions\/v1)/, r=>r.abort());
  await p.route(/cdn\.jsdelivr\.net\/npm\/@supabase/, r=>r.fulfill({contentType:'application/javascript', body:stub}));
  await p.route(/localhost:8765\/(index\.html)?(\?.*)?$/, async r => { const res = await fetch('http://localhost:8765/index.html'); r.fulfill({status:200, contentType:'text/html', body:(await res.text()).replace(/ integrity="sha384-Rj26[^"]*"/,'')}); });
  await p.goto('http://localhost:8765/',{waitUntil:'load'}); await p.waitForTimeout(2000);
  await p.click('.tab[data-view=trends]'); await p.waitForTimeout(500);
  const tr = (await p.textContent('section[aria-label=Training]')).replace(/\s+/g,' ');
  ok('Training section with streaks', /Week streak/.test(tr) && /This week/.test(tr), tr.slice(0,120));
  await p.click('[data-action=musclePeriod][data-p="30"]'); await p.waitForTimeout(300);
  ok('Body map and muscle bars (30 days)', !!(await p.$('svg.bodymap')) && (await p.$$('.mbar')).length>=2, (await p.$$eval('.mbar', xs=>xs.map(x=>x.textContent.replace(/\s+/g,' ').trim()))).join(' | '));
  await p.click('[data-fold=t-month] summary'); await p.waitForTimeout(200);
  ok('Monthly report', /Workouts/.test(await p.textContent('[data-fold=t-month]')));
  await p.click('[data-fold=t-year] summary'); await p.waitForTimeout(200);
  ok('Year in review with month chart', /Best month/.test(await p.textContent('[data-fold=t-year]')) && !!(await p.$('[data-fold=t-year] svg.chart')));
  await p.click('[data-fold=t-body] summary'); await p.waitForTimeout(200);
  await p.fill('[data-ms=waist]','84'); await p.fill('[data-ms=arms]','36.5'); await p.click('#msform button[type=submit]'); await p.waitForTimeout(300);
  ok('Measurements saved and listed', /Waist/.test(await p.textContent('.mlist')) && /84/.test(await p.textContent('.mlist')));
  await p.fill('#ms_date', '2026-09-01'); await p.fill('[data-ms=waist]','87'); await p.click('#msform button[type=submit]'); await p.waitForTimeout(300);
  ok('Change since first', /-3 since/.test((await p.textContent('.mlist')).replace(/\s+/g,' ')), (await p.textContent('.mlist')).replace(/\s+/g,' '));
  // photo upload (fake storage)
  const png = __dirname+'/label.png';
  await p.setInputFiles('#ph_file', png); await p.waitForTimeout(800);
  await p.selectOption('#ph_pose','side'); await p.setInputFiles('#ph_file', png); await p.waitForTimeout(800);
  ok('Two photos shown', (await p.$$('.ph')).length===2, String((await p.$$('.ph')).length));
  await p.click('[data-action=photoCompare]'); await p.waitForTimeout(300);
  ok('Compare side by side', (await p.$$('.pcompare img')).length===2); await p.click('#pc_ok');
  await p.click('[data-action=photoDel] >> nth=0'); await p.waitForTimeout(400);
  ok('Photo deleted', (await p.$$('.ph')).length===1);
  await p.screenshot({path:__dirname+'/trends-new.png', fullPage:true});
  ok('No page errors', !errs.length, errs.join(' | ')); console.log(out.join('\n')); await b.close(); })();
